import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'}; const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const db=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
async function sha256(value:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({valid:false,message:'Method not allowed.'},405);try{const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({valid:false,message:'Authentication required.'},401);const supabase=db();const{data:userData,error:userError}=await supabase.auth.getUser(auth.slice(7));const user=userData.user;if(userError||!user)return json({valid:false,message:'Invalid session.'},401);const body=await req.json().catch(()=>({}));if(!['activate','status'].includes(body.action))return json({valid:false,message:'Unsupported license action.'},400);if(!body.deviceId||typeof body.deviceId!=='string'||body.deviceId.length<8)return json({valid:false,message:'Device identity is required.'},400);
if(body.action==='status'){const deviceHash=await sha256(body.deviceId);const{data:device}=await supabase.from('license_device_activations').select('license_id').eq('user_id',user.id).eq('device_hash',deviceHash).is('revoked_at',null).maybeSingle();if(device?.license_id){const{data:linked}=await supabase.from('user_licenses').select('license_id,licenses!inner(id,active,expires_at,revoked_at,plan_key,package_key,included_signals,used_signals,carryover_signals,carryover_credit_lsl,price_paid_lsl)').eq('user_id',user.id).eq('license_id',device.license_id).maybeSingle();if(linked?.licenses){const l:any=linked.licenses;if(l.active&&!l.revoked_at&&(!l.expires_at||new Date(l.expires_at).getTime()>Date.now())){let pkg:any=null;if(l.package_key){const{data:p}=await supabase.from('smartvibe_subscription_packages').select('*').eq('package_key',l.package_key).maybeSingle();pkg=p;}const included=Number(l.included_signals??pkg?.included_signals??0);const used=Number(l.used_signals??0);const pending=await supabase.from('smartvibe_signal_usage').select('id',{count:'exact',head:true}).eq('user_id',user.id).eq('license_id',l.id).eq('status','PENDING');const unused=await supabase.from('smartvibe_signal_usage').select('id',{count:'exact',head:true}).eq('user_id',user.id).eq('license_id',l.id).eq('status','UNUSED');return json({valid:true,message:'License active.',expiresAt:l.expires_at??null,plan:l.plan_key??pkg?.plan_key??'professional',packageKey:l.package_key??null,packageName:pkg?.display_name??null,pricePaidLsl:Number(l.price_paid_lsl??pkg?.price_lsl??0),includedSignals:included,signalsUsed:used,signalsRemaining:Math.max(0,included-used),signalsPending:Number(pending.count??0),signalsUnused:Number(unused.count??0),carryoverSignals:Number(l.carryover_signals??0),carryoverCreditLsl:Number(l.carryover_credit_lsl??0),scannerAccess:Boolean(pkg?.scanner_access),whatsappGroupAccess:Boolean(pkg?.whatsapp_group_access),allServicesAccess:Boolean(pkg?.all_services_access)});}}}
}
return json({valid:false,message:'An active SmartVibe license is required.'});}
if(typeof body.token!=='string'||!/^SVTN-[A-F0-9]{36}$/.test(body.token.trim().toUpperCase()))return json({valid:false,message:'Invalid activation token.'},400);const tokenHash=await sha256(body.token.trim().toUpperCase());const deviceHash=await sha256(body.deviceId);const{data,error}=await supabase.rpc('redeem_license',{p_token_hash:tokenHash,p_user_id:user.id,p_device_hash:deviceHash});if(error)throw error;const result=data?.[0];if(!result)return json({valid:false,message:'License service returned no result.'},500);return json({valid:!!result.valid,message:result.message,expiresAt:result.expires_at??null});
}catch(error){console.error(error);return json({valid:false,message:'License service unavailable.'},500);}});
