import { useState } from 'react';
import { Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import * as Linking from 'expo-linking';
import { Button, Card, Screen, C } from '@/components/ui';
import { SmartVibeLogo } from '@/components/SmartVibeBrand';
import { supabase } from '@/lib/supabase';

export default function Auth(){
 const router=useRouter(); const [register,setRegister]=useState(false); const [username,setUsername]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false); const [resetMode,setResetMode]=useState(false);
 async function submit(){setError('');setNotice(''); if(!supabase)return setError('Supabase is not configured.'); if(!email.trim())return setError('Enter your email address.'); if(password.length<8)return setError('Password must be at least 8 characters.'); setBusy(true); try{if(register){if(!username.trim())throw new Error('Enter a username.'); const {data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{username:username.trim()}}});if(error)throw error;if(data.session)router.replace('/license');else setNotice('Account created. Check your email if confirmation is enabled.');}else{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;router.replace('/license');}}catch(e:any){setError(e?.message??'Authentication failed.')}finally{setBusy(false)}}
 async function sendReset(){setError('');setNotice('');if(!supabase)return setError('Supabase is not configured.');if(!email.trim())return setError('Enter your email address first.');setBusy(true);try{const redirectTo=Linking.createURL('reset-password');const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo});if(error)throw error;setNotice('Password reset instructions have been sent. Open the email on this device and follow the link.');}catch(e:any){setError(e?.message??'Unable to send password reset instructions.')}finally{setBusy(false)}}
 if(resetMode)return <Screen><View style={{flex:1,justifyContent:'center'}}><View style={{alignItems:'center',marginBottom:14}}><SmartVibeLogo width={310} height={93}/></View><Text style={{fontSize:12,fontWeight:'900',color:C.cyan,letterSpacing:1.5,textAlign:'center'}}>ACCOUNT RECOVERY</Text><Text style={{fontSize:34,lineHeight:40,fontWeight:'900',color:C.ink,marginTop:8,textAlign:'center'}}>Reset password</Text><Text style={{color:C.muted,fontSize:15,lineHeight:22,marginTop:8,textAlign:'center'}}>Enter your account email and SmartVibe will send password reset instructions.</Text><Card><Text style={{fontWeight:'900',color:C.ink}}>Email</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoCorrect={false} placeholder="you@example.com" placeholderTextColor={C.muted} style={input}/>{notice?<Text style={{color:C.green,marginTop:10,lineHeight:20}}>{notice}</Text>:null}{error?<Text style={{color:C.red,marginTop:10,lineHeight:20}}>{error}</Text>:null}</Card><Button title={busy?'Sending…':'Send reset instructions'} onPress={sendReset} disabled={busy}/><Button title="Back to sign in" variant="secondary" onPress={()=>{setResetMode(false);setError('');setNotice('')}} disabled={busy}/></View></Screen>;
 return <Screen><View style={{flex:1,justifyContent:'center'}}><View style={{alignItems:'center',marginBottom:14}}><SmartVibeLogo width={310} height={93}/></View><Text style={{fontSize:12,fontWeight:'900',color:C.cyan,letterSpacing:1.5,textAlign:'center'}}>SECURE CLIENT ACCESS</Text><Text style={{fontSize:34,lineHeight:40,fontWeight:'900',color:C.ink,marginTop:8,textAlign:'center'}}>{register?'Create account':'Welcome back'}</Text><Text style={{color:C.muted,fontSize:15,lineHeight:22,marginTop:8,textAlign:'center'}}>{register?'Create your SmartVibe trading account.':'Sign in to continue to your SmartVibe trading workspace.'}</Text>{register?<Card><Text style={{fontWeight:'900',color:C.ink}}>Username</Text><TextInput value={username} onChangeText={setUsername} autoCapitalize="none" autoCorrect={false} placeholder="Choose a username" placeholderTextColor={C.muted} style={input}/></Card>:null}<Card><Text style={{fontWeight:'900',color:C.ink}}>Email</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoCorrect={false} placeholder="you@example.com" placeholderTextColor={C.muted} style={input}/><Text style={{fontWeight:'900',marginTop:14,color:C.ink}}>Password</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry autoCapitalize="none" autoCorrect={false} placeholder="Minimum 8 characters" placeholderTextColor={C.muted} style={input}/>{error?<Text style={{color:C.red,marginTop:10,lineHeight:20}}>{error}</Text>:null}{notice?<Text style={{color:C.green,marginTop:10,lineHeight:20}}>{notice}</Text>:null}</Card><Button title={busy?'Please wait…':register?'Create account':'Sign in'} onPress={submit} disabled={busy}/>{!register?<Button title="Forgot password?" variant="secondary" onPress={()=>{setResetMode(true);setError('');setNotice('')}} disabled={busy}/>:null}<Button title={register?'I already have an account':'Create a new account'} variant="secondary" onPress={()=>{setError('');setNotice('');setRegister(!register)}} disabled={busy}/></View></Screen>
}
const input={borderWidth:1 as const,borderColor:C.border,borderRadius:14,padding:14,marginTop:8,fontSize:16,color:C.ink,backgroundColor:C.card};