import { useEffect, useState } from 'react';
import { Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Button, Card, Screen, C } from '@/components/ui';
import { supabase } from '@/lib/supabase';

export default function Auth(){
 const router=useRouter(); const [register,setRegister]=useState(false); const [username,setUsername]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{supabase?.auth.getSession().then(({data})=>{if(data.session)router.replace('/(tabs)/markets')}).catch(()=>{});},[router]);
 async function submit(){setError(''); if(!supabase)return setError('Supabase is not configured.'); if(password.length<8)return setError('Password must be at least 8 characters.'); setBusy(true); try{if(register){const {data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{username:username.trim()}}});if(error)throw error;if(data.session)router.replace('/(tabs)/markets');else setError('Account created. Check your email if confirmation is enabled.');}else{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;router.replace('/(tabs)/markets');}}catch(e:any){setError(e?.message??'Authentication failed.')}finally{setBusy(false)}}
 return <Screen><View style={{flex:1,justifyContent:'center'}}><Text style={{fontSize:13,fontWeight:'900',color:C.blue,letterSpacing:1}}>SMARTVIBE TRADING NETWORK</Text><Text style={{fontSize:40,fontWeight:'900',color:C.midnight,marginTop:8}}>{register?'Create account':'Welcome back'}</Text><Text style={{color:C.muted,fontSize:16,lineHeight:24,marginTop:8}}>{register?'Create your SmartVibe Trading Network account.':'Sign in to continue to your SmartVibe trading workspace.'}</Text>{register?<Card><Text style={{fontWeight:'900'}}>Username</Text><TextInput value={username} onChangeText={setUsername} autoCapitalize="none" style={input}/></Card>:null}<Card><Text style={{fontWeight:'900'}}>Email</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" style={input}/><Text style={{fontWeight:'900',marginTop:14}}>Password</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry style={input}/>{error?<Text style={{color:C.red,marginTop:10,lineHeight:20}}>{error}</Text>:null}</Card><Button title={busy?'Please wait…':register?'Create account':'Sign in'} onPress={submit}/><Button title={register?'I already have an account':'Create a new account'} variant="secondary" onPress={()=>{setError('');setRegister(!register)}}/></View></Screen>
}
const input={borderWidth:1 as const,borderColor:'#E6EBF1',borderRadius:14,padding:14,marginTop:8,fontSize:16};
