import { useEffect, useState } from 'react';
import { Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Button, Card, Screen, C } from '@/components/ui';
import { SmartVibeLogo } from '@/components/SmartVibeBrand';
import { supabase } from '@/lib/supabase';

export default function Auth(){
 const router=useRouter(); const [register,setRegister]=useState(false); const [username,setUsername]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{supabase?.auth.getSession().then(({data})=>{if(data.session)router.replace('/license')}).catch(()=>{});},[router]);
 async function submit(){setError(''); if(!supabase)return setError('Supabase is not configured.'); if(!email.trim())return setError('Enter your email address.'); if(password.length<8)return setError('Password must be at least 8 characters.'); setBusy(true); try{if(register){if(!username.trim())throw new Error('Enter a username.'); const {data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{username:username.trim()}}});if(error)throw error;if(data.session)router.replace('/license');else setError('Account created. Check your email if confirmation is enabled.');}else{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;router.replace('/license');}}catch(e:any){setError(e?.message??'Authentication failed.')}finally{setBusy(false)}}
 return <Screen><View style={{flex:1,justifyContent:'center'}}><View style={{alignItems:'center',marginBottom:14}}><SmartVibeLogo width={310} height={93}/></View><Text style={{fontSize:12,fontWeight:'900',color:C.cyan,letterSpacing:1.5,textAlign:'center'}}>SECURE CLIENT ACCESS</Text><Text style={{fontSize:34,lineHeight:40,fontWeight:'900',color:C.ink,marginTop:8,textAlign:'center'}}>{register?'Create account':'Welcome back'}</Text><Text style={{color:C.muted,fontSize:15,lineHeight:22,marginTop:8,textAlign:'center'}}>{register?'Create your SmartVibe trading account.':'Sign in to continue to your SmartVibe trading workspace.'}</Text>{register?<Card><Text style={{fontWeight:'900',color:C.ink}}>Username</Text><TextInput value={username} onChangeText={setUsername} autoCapitalize="none" placeholder="Choose a username" placeholderTextColor={C.muted} style={input}/></Card>:null}<Card><Text style={{fontWeight:'900',color:C.ink}}>Email</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="you@example.com" placeholderTextColor={C.muted} style={input}/><Text style={{fontWeight:'900',marginTop:14,color:C.ink}}>Password</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Minimum 8 characters" placeholderTextColor={C.muted} style={input}/>{error?<Text style={{color:C.red,marginTop:10,lineHeight:20}}>{error}</Text>:null}</Card><Button title={busy?'Please wait…':register?'Create account':'Sign in'} onPress={submit} disabled={busy}/><Button title={register?'I already have an account':'Create a new account'} variant="secondary" onPress={()=>{setError('');setRegister(!register)}} disabled={busy}/></View></Screen>
}
const input={borderWidth:1 as const,borderColor:C.border,borderRadius:14,padding:14,marginTop:8,fontSize:16,color:C.ink,backgroundColor:C.card};
