import { useState } from 'react';
import { Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import * as SecureStore from 'expo-secure-store';
import { Button, Card, Screen, C } from '@/components/ui';
import { validateLicense } from '@/lib/backend';

function uuidV4(){const bytes=Array.from({length:16},()=>Math.floor(Math.random()*256));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=bytes.map(b=>b.toString(16).padStart(2,'0')).join('');return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;}

export default function License(){const router=useRouter();const[token,setToken]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function activate(){setError('');if(!token.trim())return setError('Enter your license token.');setBusy(true);try{let deviceId=await SecureStore.getItemAsync('smartvibe_device_id');if(!deviceId){deviceId=uuidV4();await SecureStore.setItemAsync('smartvibe_device_id',deviceId);}const result=await validateLicense({token:token.trim(),action:'activate',deviceId});if(!result.valid)throw new Error(result.message);await SecureStore.setItemAsync('smartvibe_license_active','1');await SecureStore.setItemAsync('smartvibe_license_token',token.trim());router.replace('/risk')}catch(e:any){setError(e?.message??'License validation failed.')}finally{setBusy(false)}}return <Screen><View style={{flex:1,justifyContent:'center'}}><Text style={{fontSize:13,fontWeight:'900',color:C.blue,letterSpacing:1}}>SMARTVIBE TRADING NETWORK</Text><Text style={{fontSize:40,fontWeight:'900',color:C.midnight,marginTop:8}}>Activate app</Text><Text style={{color:C.muted,fontSize:16,lineHeight:24,marginTop:10}}>Enter your SmartVibe license token. A valid token is required before the trading workspace can be opened.</Text><Card><Text style={{fontWeight:'900',marginBottom:8}}>License token</Text><TextInput value={token} onChangeText={setToken} autoCapitalize="characters" placeholder="SVTN-…" style={{borderWidth:1,borderColor:'#E6EBF1',borderRadius:14,padding:15,fontSize:16}}/>{error?<Text style={{color:C.red,marginTop:8}}>{error}</Text>:null}</Card><Button title={busy?'Activating…':'Activate license'} onPress={activate}/></View></Screen>}
