import { useEffect, useState } from 'react';
import { Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Button, Card, Screen, C } from '@/components/ui';
import { SmartVibeLogo } from '@/components/SmartVibeBrand';
import { supabase } from '@/lib/supabase';

export default function ResetPassword(){
 const router=useRouter(); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [ready,setReady]=useState(false);
 useEffect(()=>{let active=true;(async()=>{if(!supabase){if(active)setError('Supabase is not configured.');return;}const {data}=await supabase.auth.getSession();if(active){setReady(!!data.session);if(!data.session)setError('This reset link is invalid or has expired. Request a new one from Sign in.');}})();return()=>{active=false}},[]);
 async function update(){setError('');setNotice('');if(password.length<8)return setError('Password must be at least 8 characters.');if(password!==confirm)return setError('Passwords do not match.');if(!supabase)return setError('Supabase is not configured.');setBusy(true);try{const {error}=await supabase.auth.updateUser({password});if(error)throw error;setNotice('Password updated successfully. You can now sign in with your new password.');setPassword('');setConfirm('');setTimeout(()=>router.replace('/auth'),900);}catch(e:any){setError(e?.message??'Unable to update your password. The reset link may have expired.')}finally{setBusy(false)}}
 return <Screen><View style={{flex:1,justifyContent:'center'}}><View style={{alignItems:'center',marginBottom:14}}><SmartVibeLogo width={310} height={93}/></View><Text style={{fontSize:12,fontWeight:'900',color:C.cyan,letterSpacing:1.5,textAlign:'center'}}>ACCOUNT RECOVERY</Text><Text style={{fontSize:34,lineHeight:40,fontWeight:'900',color:C.ink,marginTop:8,textAlign:'center'}}>Set new password</Text><Text style={{color:C.muted,fontSize:15,lineHeight:22,marginTop:8,textAlign:'center'}}>Choose a new password for your SmartVibe account.</Text>{ready?<Card><Text style={{fontWeight:'900',color:C.ink}}>New password</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry autoCapitalize="none" autoCorrect={false} placeholder="Minimum 8 characters" placeholderTextColor={C.muted} style={input}/><Text style={{fontWeight:'900',marginTop:14,color:C.ink}}>Confirm password</Text><TextInput value={confirm} onChangeText={setConfirm} secureTextEntry autoCapitalize="none" autoCorrect={false} placeholder="Repeat your password" placeholderTextColor={C.muted} style={input}/>{error?<Text style={{color:C.red,marginTop:10,lineHeight:20}}>{error}</Text>:null}{notice?<Text style={{color:C.green,marginTop:10,lineHeight:20}}>{notice}</Text>:null}</Card>:<Card><Text style={{color:C.red,lineHeight:20}}>{error}</Text></Card>}<Button title={busy?'Updating…':'Update password'} onPress={update} disabled={busy||!ready}/><Button title="Back to sign in" variant="secondary" onPress={()=>router.replace('/auth')} disabled={busy}/></View></Screen>
}
const input={borderWidth:1 as const,borderColor:C.border,borderRadius:14,padding:14,marginTop:8,fontSize:16,color:C.ink,backgroundColor:C.card};
