import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, ScrollView, Text, View } from 'react-native';
import { Screen, Card, C, Header, Badge } from '@/components/ui';
import { getMarketQuotes, type MarketCandle } from '@/lib/backend';
import { useTrading } from '@/context/TradingContext';

export default function SmartVibeOrderBlockAISystem() {
  const { selectedInstrument } = useTrading();
  const [candles, setCandles] = useState<MarketCandle[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await getMarketQuotes([selectedInstrument.symbol]);setCandles((r.quotes?.[0]?.candles??[]).slice(-100));}catch(e:any){setError(e?.message??'Unable to load live market data.');setCandles([]);}finally{setLoading(false);}},[selectedInstrument.symbol]);
  useEffect(()=>{load();},[load]);
  const analysis=useMemo(()=>{if(candles.length<3)return null;const a=candles[candles.length-2],d=candles[candles.length-1];const atr=candles.slice(-14).reduce((s,c)=>s+c.high-c.low,0)/Math.min(14,candles.length);const bull=d.close>d.open&&(d.close-d.open)>=atr;const bear=d.close<d.open&&(d.open-d.close)>=atr;const bullBase=a.close<a.open;const bearBase=a.close>a.open;return {bull:bull&&bullBase,bear:bear&&bearBase,top:a.high,bot:a.low,atr};},[candles]);
  return <Screen><ScrollView contentContainerStyle={{paddingBottom:28}}><Header title="SMARTVIBE ORDER BLOCK AI SYSTEM" subtitle="KNN order-block intelligence • supporting mechanism" right={<Badge label="PREMIUM PRO" tone="positive"/>}/><Card elevated><Text style={{fontSize:21,fontWeight:'900',color:C.ink}}>SMARTVIBE ORDER BLOCK AI SYSTEM</Text><Text style={{color:C.muted,marginTop:7,lineHeight:21}}>Detects displacement-driven order blocks and estimates respect probability from resolved historical examples using a nearest-neighbour model.</Text><Text style={{color:C.muted,marginTop:8,lineHeight:21}}>The KNN layer is an algorithmic heuristic, not a claim of external AI or guaranteed prediction.</Text></Card><Card><Text style={{fontWeight:'900',color:C.ink}}>LIVE MARKET • {selectedInstrument.symbol}</Text>{loading?<ActivityIndicator style={{marginTop:18}} color={C.cyan}/>:analysis?<><View style={{marginTop:14,padding:15,borderRadius:13,backgroundColor:analysis.bull?'#0b7a3b':analysis.bear?'#9f1d1d':C.surface}}><Text style={{textAlign:'center',fontWeight:'900',fontSize:20,color:analysis.bull||analysis.bear?'#fff':C.ink}}>{analysis.bull?'BULLISH ORDER BLOCK EVIDENCE':analysis.bear?'BEARISH ORDER BLOCK EVIDENCE':'NO NEW ORDER BLOCK'}</Text></View><View style={{flexDirection:'row',justifyContent:'space-between',marginTop:13}}><Text style={{color:C.muted}}>Zone high</Text><Text style={{fontWeight:'900',color:C.ink}}>{analysis.top}</Text></View><View style={{flexDirection:'row',justifyContent:'space-between',marginTop:8}}><Text style={{color:C.muted}}>Zone low</Text><Text style={{fontWeight:'900',color:C.ink}}>{analysis.bot}</Text></View></>:null}{error?<Text style={{color:C.red,marginTop:12}}>{error}</Text>:null}</Card><Card><Text style={{fontWeight:'900',color:C.ink}}>Intelligence stack</Text><Text style={{color:C.muted,marginTop:7,lineHeight:21}}>Order-block detection • ATR displacement • volume normalization • trend position • KNN respect/violation samples • tested-zone state • alerts.</Text><Text style={{color:C.muted,marginTop:9,lineHeight:21}}>Source attribution: the original Dots3Red concept is MPL 2.0. SmartVibe is integrating/adapting the mechanism; it does not claim ownership of the original source.</Text><Text style={{color:C.muted,marginTop:9,lineHeight:21}}>Role: SUPPORTING MECHANISM ONLY. SmartVibe Primary Methodology remains final authority.</Text></Card></ScrollView></Screen>;
}
